/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "mp2_constants.h"

namespace mp2 {

const mp2Constants g_mp2_constants;

mp2Constants::mp2Constants() {
}

} // namespace

