/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mp2_CONSTANTS_H
#define mp2_CONSTANTS_H

#include "mp2_types.h"

namespace mp2 {

class mp2Constants {
 public:
  mp2Constants();

};

extern const mp2Constants g_mp2_constants;

} // namespace

#endif
