// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "MyService.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::mp2;

class MyServiceHandler : virtual public MyServiceIf {
 public:
  MyServiceHandler() {
    // Your initialization goes here
  }

  void get_predecessor(finger_entry& _return) {
    // Your implementation goes here
    printf("get_predecessor\n");
  }

  void get_successor(finger_entry& _return) {
    // Your implementation goes here
    printf("get_successor\n");
  }

  void find_successor(finger_entry& _return, const int32_t id) {
    // Your implementation goes here
    printf("find_successor\n");
  }

  void find_predecessor(finger_entry& _return, const int32_t id) {
    // Your implementation goes here
    printf("find_predecessor\n");
  }

  void closest_preceding_finger(finger_entry& _return, const int32_t id) {
    // Your implementation goes here
    printf("closest_preceding_finger\n");
  }

  void notify(const finger_entry& n) {
    // Your implementation goes here
    printf("notify\n");
  }

  void gateway_add_file_self(std::string& _return, const std::string& name, const std::string& content) {
    // Your implementation goes here
    printf("gateway_add_file_self\n");
  }

  void gateway_add_file_other(std::string& _return, const std::string& name, const std::string& content) {
    // Your implementation goes here
    printf("gateway_add_file_other\n");
  }

  void gateway_del_file_self(std::string& _return, const std::string& name) {
    // Your implementation goes here
    printf("gateway_del_file_self\n");
  }

  void gateway_del_file_other(std::string& _return, const std::string& name) {
    // Your implementation goes here
    printf("gateway_del_file_other\n");
  }

  void gateway_get_file_self(std::string& _return, const std::string& name) {
    // Your implementation goes here
    printf("gateway_get_file_self\n");
  }

  void gateway_get_file_other(std::string& _return, const std::string& name) {
    // Your implementation goes here
    printf("gateway_get_file_other\n");
  }

  void gateway_get_self_table(std::string& _return) {
    // Your implementation goes here
    printf("gateway_get_self_table\n");
  }

  void gateway_get_other_table(std::string& _return, const int32_t id) {
    // Your implementation goes here
    printf("gateway_get_other_table\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<MyServiceHandler> handler(new MyServiceHandler());
  shared_ptr<TProcessor> processor(new MyServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

